# stage 1
FROM rust:1-alpine3.16

WORKDIR /forbuild

COPY ./ /forbuild
ENV RUSTFLAGS="-C target-feature=-crt-static"
RUN apk update
RUN apk add --no-cache musl-dev
RUN cargo build --release

# stage 2
FROM alpine:3.16

WORKDIR /fordeploy

COPY --from=0 /forbuild/target/release/crate_test .

EXPOSE 8080
RUN apk update
RUN apk add --no-cache libgcc
CMD ["./crate_test"]
